data_conf:
  num_inputs: 3
  num_outputs: 1
  output_index: 0

transform_conf:
  transform_input:
    transform_data: true
    transformer_class: PowerTransformer
    transformer_options:
      method: yeo-johnson
      standardize: true
    columns: null
  transform_output:
    transform_data: false
    transformer_class: MinMaxScaler
    transformer_options: null
    columns: null

training_conf:
  model_class: SingleGPRBF
  likelihood_class: GaussianLikelihood
  learning_iterations: 100
  botorch: false
  debug: True
  optimizer:
    optimizer_class: Adam
    optimizer_options:
      lr: 0.1

testing_conf:
  test: false
  test_size: 0.2
  strat_shuffle_split: false
  kfold: false
  kfold_bins: null