name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: ci-env
          cache-environment: true
          cache-downloads: true
      - name: install package
        run: | 
          micromamba activate ci-env && pip install -e . --use-pep517
      - uses: astral-sh/ruff-action@v3

      - name: Lint code
        run: micromamba run -n ci-env ruff check --fix .

      - name: Format code
        run: micromamba run -n ci-env ruff format .

      - name: Run tests
        run: micromamba run -n ci-env pytest .

  docs:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: ci-env
          cache-environment: true
          cache-downloads: true

      - name: Build HTML with Sphinx
        uses: ammaraskar/sphinx-action@master

      - name: Upload HTML Docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/

      - name: Deploy (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
