name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Add Conda to PATH
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.conda/pkgs
            ~/.conda/envs
          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}

      - name: Create Conda environment
        run: |
          conda env create --name ci-env --file environment.yml || echo "Env already exists"
          conda activate ci-env

      - name: Use Conda environment
        run: |
          source activate ci-env
          which python
          python --version

      - uses: astral-sh/ruff-action@v3

      - name: Lint code
        run: |
          source activate ci-env
          ruff check --fix .

      - name: Format code
        run: |
          source activate ci-env
          ruff format .

      - name: Run tests
        run: |
          source activate ci-env
          pytest .

  docs:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Add Conda to PATH
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.conda/pkgs
            ~/.conda/envs
          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}

      - name: Create Conda environment
        run: |
          conda env create --name ci-env --file environment.yml || echo "Env already exists"
          conda activate ci-env

      - name: Build HTML with Sphinx
        uses: ammaraskar/sphinx-action@master

      - name: Upload HTML Docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/

      - name: Deploy (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
